[package]
name = "catppuccin"
version = "0.0.1"
compiler = "0.13.0"
repository = "https://github.com/soks-kat/catppuccin-typst"
# homepage = "https://cetz-package.github.io/"
entrypoint = "src/lib.typ"
authors = [
  "Soks Kat <https://github.com/soks-kat>",
]
categories = [ "theming" ]
license = "LGPL-3.0-or-later"
description = "A colourfull theming system for typst."
keywords = [ "theming", "catppuccin", "kanagawa" ]
# exclude = [ "/gallery/*", "manual.pdf", "manual.typ" ]
